import { db, recipesTable, ingredientsTable, creationsTable, plansTable } from "@workspace/db";
import { logger } from "./logger";

/**
 * Ingredients: SmoothieKing's original 15 plus 28 from the elicitation
 * prototype, 43 in total.
 *
 * Merge rules, and who wins where:
 *
 *   Reader-facing copy is SmoothieKing's. The original 15 keep their Korean
 *   names, descriptions and skinBenefitKey untouched. The 28 new rows carry
 *   plain factual one-liners rather than copy written in that voice — that
 *   register belongs to whoever wrote it.
 *
 *   Build properties (slot, servingGrams, flavors, contains, animal) come
 *   from the prototype, because nothing here had them and a recipe cannot be
 *   generated or safety-checked without them. `contains` is what the
 *   allergen filter reads, so an almond butter is excluded by a tree-nut
 *   allergy through structure rather than through matching on its name.
 *
 *   Nutrition is USDA FoodData Central, each row carrying its own fdcId so a
 *   figure traces to one specific record. Four rows have no sugar figure and
 *   say so in nutritionNote: dragon fruit, collagen and pea protein have no
 *   entry in USDA's curated datasets at all, and USDA publishes no sugar for
 *   chia. Near-zero is a reasonable guess for two of those and a guess is
 *   not what this column is for.
 *
 *   Goal vocabulary is SmoothieKing's. `gut-health` and `energy-focus` are
 *   new; the prototype's `lean-light` was dropped rather than mapped onto
 *   `detox-clarity`, which means something else.
 */
const ingredients = [
  {
    name: "Mango",
    category: "fruit",
    benefits: ["anti-inflammatory", "glowy-skin", "gut-health"],
    skinBenefitKey: "vitamin-c-boost",
    description: "Rich in vitamins A and C, mango brightens and evens skin tone while fighting free radicals — the K-beauty equivalent of vitamin C serum, in fruit form.",
    koreanName: "망고",
    nutrientHighlights: ["Vitamin C", "Vitamin A", "Beta-Carotene", "Folate"],
    slot: "flavor",
    servingGrams: 120.0,
    hex: "#F2AE4B",
    flavors: ["tropical"],
    contains: [],
    animal: false,
    kcal: 60.0,
    proteinG: 0.82,
    fatG: 0.38,
    carbG: 14.98,
    sugarG: 13.66,
    fiberG: 1.6,
    fdcId: 169910,
    fdcDescription: "Mangos, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Dragon Fruit",
    category: "fruit",
    benefits: ["glowy-skin", "hydration"],
    skinBenefitKey: "radiance",
    description: "The hyaluronic acid of fruits. Dragon fruit is a hydration powerhouse with betalains that reduce oxidative stress and promote a luminous, dewy complexion.",
    koreanName: "드래곤 프루트",
    nutrientHighlights: ["Betalains", "Vitamin C", "Iron", "Magnesium"],
    slot: "flavor",
    servingGrams: 100,
    hex: "#E86AA6",
    flavors: ["tropical"],
    contains: [],
    animal: false,
    kcal: null,
    proteinG: null,
    fatG: null,
    carbG: null,
    sugarG: null,
    fiberG: null,
    fdcId: null,
    fdcDescription: null,
    fdcDataType: null,
    nutritionNote: "No pitaya/dragon fruit record in Foundation or SR Legacy; search returned Abiyuch, an unrelated fruit.",
  },
  {
    name: "Turmeric",
    category: "adaptogen",
    benefits: ["anti-inflammatory", "glowy-skin"],
    skinBenefitKey: "brightening",
    description: "Curcumin, the active compound in turmeric, has been used in Korean and Ayurvedic beauty rituals for centuries. It inhibits melanin production and reduces redness at the cellular level.",
    koreanName: "강황",
    nutrientHighlights: ["Curcumin", "Manganese", "Iron", "Vitamin B6"],
    slot: "functional",
    servingGrams: 3.0,
    hex: "#D69A21",
    flavors: ["vanilla-spice"],
    contains: [],
    animal: false,
    kcal: 312.0,
    proteinG: 9.68,
    fatG: 3.25,
    carbG: 67.14,
    sugarG: 3.21,
    fiberG: 22.7,
    fdcId: 172231,
    fdcDescription: "Spices, turmeric, ground",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Spirulina",
    category: "superfood",
    benefits: ["detox-clarity", "anti-inflammatory", "protein-power"],
    skinBenefitKey: "detox-clarity",
    description: "Nature's most concentrated protein — 70% by weight. Spirulina's phycocyanin binds to toxins and carries them out of the body, leaving skin noticeably clearer within weeks.",
    koreanName: "스피루리나",
    nutrientHighlights: ["Phycocyanin", "Complete Protein", "Iron", "B12"],
    slot: "functional",
    servingGrams: 5,
    hex: "#2E5E4E",
    flavors: ["green-earthy"],
    contains: [],
    animal: false,
    kcal: 290.0,
    proteinG: 57.47,
    fatG: 7.72,
    carbG: 23.9,
    sugarG: 3.1,
    fiberG: 3.6,
    fdcId: 170495,
    fdcDescription: "Seaweed, spirulina, dried",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Collagen Peptides",
    category: "protein",
    benefits: ["glowy-skin", "protein-power"],
    skinBenefitKey: "collagen-synthesis",
    description: "Hydrolyzed marine collagen — the gold standard in K-beauty ingestible skincare. Clinical studies confirm significant improvement in skin elasticity and moisture retention after 8 weeks.",
    koreanName: "콜라겐 펩타이드",
    nutrientHighlights: ["Glycine", "Proline", "Hydroxyproline", "Type I & III Collagen"],
    slot: "functional",
    servingGrams: 12.0,
    hex: "#F2EDE0",
    flavors: [],
    contains: [],
    animal: true,
    kcal: null,
    proteinG: null,
    fatG: null,
    carbG: null,
    sugarG: null,
    fiberG: null,
    fdcId: null,
    fdcDescription: null,
    fdcDataType: null,
    nutritionNote: "No collagen peptide record in Foundation or SR Legacy; Branded only.",
  },
  {
    name: "Coconut Water",
    category: "liquid",
    benefits: ["energy-focus", "hydration"],
    skinBenefitKey: "electrolyte-hydration",
    description: "Nature's isotonic drink. Coconut water matches the electrolyte profile of human plasma — it doesn't just hydrate, it rehydrates at a cellular level, plumping skin from within.",
    koreanName: "코코넛 워터",
    nutrientHighlights: ["Potassium", "Sodium", "Magnesium", "Cytokinins"],
    slot: "liquid",
    servingGrams: 200.0,
    hex: "#EFEAD8",
    flavors: ["tropical"],
    contains: [],
    animal: false,
    kcal: 19.0,
    proteinG: 0.72,
    fatG: 0.2,
    carbG: 3.71,
    sugarG: 2.61,
    fiberG: 1.1,
    fdcId: 170174,
    fdcDescription: "Nuts, coconut water (liquid from coconuts)",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Ginger",
    category: "adaptogen",
    benefits: ["anti-inflammatory", "detox-clarity", "gut-health"],
    skinBenefitKey: "circulation-boost",
    description: "Gingerols and shogaols improve peripheral circulation, delivering oxygen and nutrients to the skin. A warming, activating ingredient — the K-beauty answer to sluggish dull skin.",
    koreanName: "생강",
    nutrientHighlights: ["Gingerols", "Shogaols", "Zinc", "Vitamin C"],
    slot: "functional",
    servingGrams: 6.0,
    hex: "#D9C48A",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 80.0,
    proteinG: 1.82,
    fatG: 0.75,
    carbG: 17.77,
    sugarG: 1.7,
    fiberG: 2.0,
    fdcId: 169231,
    fdcDescription: "Ginger root, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Avocado",
    category: "fat",
    benefits: ["glowy-skin", "hydration"],
    skinBenefitKey: "barrier-repair",
    description: "Oleic acid and vitamin E work together to repair the skin barrier and lock in moisture — the ingestible version of a rich overnight face cream. Plumping and nourishing.",
    koreanName: "아보카도",
    nutrientHighlights: ["Oleic Acid", "Vitamin E", "Vitamin K", "Folate"],
    slot: "functional",
    servingGrams: 70.0,
    hex: "#7E9B4F",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 167.0,
    proteinG: 1.96,
    fatG: 15.41,
    carbG: 8.64,
    sugarG: 0.3,
    fiberG: 6.8,
    fdcId: 171706,
    fdcDescription: "Avocados, raw, California",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Whey Protein Isolate",
    category: "protein",
    benefits: ["protein-power"],
    skinBenefitKey: null,
    description: "Cold-processed whey isolate with 90%+ protein content. Fast-absorbing and leucine-rich for immediate muscle protein synthesis. The clean, no-filler standard for serious performance.",
    koreanName: null,
    nutrientHighlights: ["Complete Amino Acid Profile", "Leucine", "BCAAs", "Glutamine"],
    slot: "protein",
    servingGrams: 30.0,
    hex: "#F5EFE2",
    flavors: [],
    contains: ["dairy"],
    animal: true,
    kcal: 352.0,
    proteinG: 78.13,
    fatG: 1.56,
    carbG: 6.25,
    sugarG: 0.0,
    fiberG: 3.1,
    fdcId: 173180,
    fdcDescription: "Beverages, Protein powder whey based",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Tomato",
    category: "vegetable",
    benefits: ["sun-ritual", "anti-inflammatory"],
    skinBenefitKey: "uv-defense",
    description: "Lycopene-dense and scientifically proven to reduce UV-induced skin damage by up to 33% with regular consumption. Korea's dermatologists call it the edible sunscreen ingredient.",
    koreanName: "토마토",
    nutrientHighlights: ["Lycopene", "Vitamin C", "Potassium", "Beta-Carotene"],
    slot: "flavor",
    servingGrams: 100,
    hex: "#D6453A",
    flavors: ["green-earthy"],
    contains: [],
    animal: false,
    kcal: 18.0,
    proteinG: 0.88,
    fatG: 0.2,
    carbG: 3.89,
    sugarG: 2.63,
    fiberG: 1.2,
    fdcId: 170457,
    fdcDescription: "Tomatoes, red, ripe, raw, year round average",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Matcha",
    category: "adaptogen",
    benefits: ["anti-inflammatory", "detox-clarity", "energy-focus"],
    skinBenefitKey: "catechin-protection",
    description: "EGCG catechins in ceremonial-grade matcha are the most potent antioxidants in the plant kingdom — neutralizing 100x more free radicals than Vitamin C. A ritual, not just a drink.",
    koreanName: "말차",
    nutrientHighlights: ["EGCG", "L-Theanine", "Chlorophyll", "Catechins"],
    slot: "functional",
    servingGrams: 5.0,
    hex: "#7FA050",
    flavors: ["green-earthy"],
    contains: [],
    animal: false,
    kcal: 315.0,
    proteinG: 20.21,
    fatG: 0.0,
    carbG: 58.66,
    sugarG: 5.53,
    fiberG: 8.5,
    fdcId: 173230,
    fdcDescription: "Beverages, tea, instant, unsweetened, powder",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Blueberry",
    category: "fruit",
    benefits: ["anti-inflammatory", "glowy-skin"],
    skinBenefitKey: "anthocyanin-glow",
    description: "Anthocyanins in blueberries cross the blood-brain barrier and stimulate collagen production directly. Wild blueberries carry 2x the antioxidant load of cultivated varieties.",
    koreanName: "블루베리",
    nutrientHighlights: ["Anthocyanins", "Resveratrol", "Vitamin C", "Manganese"],
    slot: "flavor",
    servingGrams: 80.0,
    hex: "#5B5BA0",
    flavors: ["berry"],
    contains: [],
    animal: false,
    kcal: 57.0,
    proteinG: 0.74,
    fatG: 0.33,
    carbG: 14.49,
    sugarG: 9.96,
    fiberG: 2.4,
    fdcId: 171711,
    fdcDescription: "Blueberries, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Watermelon",
    category: "fruit",
    benefits: ["hydration", "sun-ritual"],
    skinBenefitKey: "citrulline-hydration",
    description: "92% water with citrulline that converts to arginine — a vasodilator that improves blood flow and nutrient delivery to skin cells. Korean summers run on watermelon for good reason.",
    koreanName: "수박",
    nutrientHighlights: ["Citrulline", "Lycopene", "Vitamin A", "Potassium"],
    slot: "flavor",
    servingGrams: 100,
    hex: "#F2637C",
    flavors: ["tropical"],
    contains: [],
    animal: false,
    kcal: 30.0,
    proteinG: 0.61,
    fatG: 0.15,
    carbG: 7.55,
    sugarG: 6.2,
    fiberG: 0.4,
    fdcId: 167765,
    fdcDescription: "Watermelon, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Spinach",
    category: "vegetable",
    benefits: ["anti-inflammatory", "detox-clarity"],
    skinBenefitKey: "chlorophyll-detox",
    description: "Chlorophyll acts as a molecular mirror of hemoglobin, supporting oxygen-rich blood and efficient toxin removal. One of the few ingredients that simultaneously alkalizes, detoxes, and energizes.",
    koreanName: "시금치",
    nutrientHighlights: ["Chlorophyll", "Iron", "Folate", "Vitamin K"],
    slot: "flavor",
    servingGrams: 40.0,
    hex: "#3F7A3A",
    flavors: ["green-earthy"],
    contains: [],
    animal: false,
    kcal: 23.0,
    proteinG: 2.86,
    fatG: 0.39,
    carbG: 3.63,
    sugarG: 0.42,
    fiberG: 2.2,
    fdcId: 168462,
    fdcDescription: "Spinach, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Kefir",
    category: "protein",
    benefits: ["anti-inflammatory", "glowy-skin", "gut-health"],
    skinBenefitKey: "gut-skin-axis",
    description: "The gut-skin axis is the frontier of modern dermatology. Kefir's 50+ probiotic strains optimize the microbiome, reducing systemic inflammation that manifests as acne, eczema, and dullness.",
    koreanName: "케피어",
    nutrientHighlights: ["Probiotics", "Calcium", "Vitamin K2", "B Vitamins"],
    slot: "protein",
    servingGrams: 150.0,
    hex: "#F8F4EA",
    flavors: [],
    contains: ["dairy"],
    animal: true,
    kcal: 43.0,
    proteinG: 3.79,
    fatG: 1.02,
    carbG: 4.77,
    sugarG: 4.61,
    fiberG: 0.0,
    fdcId: 170904,
    fdcDescription: "Kefir, lowfat, plain, LIFEWAY",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Almond milk",
    category: "liquid",
    benefits: [],
    skinBenefitKey: null,
    description: "Unsweetened almond milk. Light, low in sugar, and a neutral base that lets other flavours lead.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "liquid",
    servingGrams: 200.0,
    hex: "#EDE4D3",
    flavors: ["vanilla-spice"],
    contains: ["tree-nut"],
    animal: false,
    kcal: 15.0,
    proteinG: 0.4,
    fatG: 0.96,
    carbG: 1.31,
    sugarG: 0.81,
    fiberG: 0.2,
    fdcId: 174832,
    fdcDescription: "Beverages, almond milk, unsweetened, shelf stable",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Oat milk",
    category: "liquid",
    benefits: [],
    skinBenefitKey: null,
    description: "Oat milk. Creamier than almond with a little natural sweetness; contains gluten.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "liquid",
    servingGrams: 200.0,
    hex: "#E8DCC6",
    flavors: ["vanilla-spice"],
    contains: ["gluten"],
    animal: false,
    kcal: 48.33,
    proteinG: 0.8,
    fatG: 2.75,
    carbG: 5.1,
    sugarG: 2.32,
    fiberG: 0.0,
    fdcId: 2257046,
    fdcDescription: "Oat milk, unsweetened, plain, refrigerated",
    fdcDataType: "Foundation",
    nutritionNote: null,
  },
  {
    name: "Whole milk",
    category: "liquid",
    benefits: ["protein-power"],
    skinBenefitKey: null,
    description: "Whole milk. The richest base here, and the one that carries the most protein per pour.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "liquid",
    servingGrams: 200.0,
    hex: "#FAF7F0",
    flavors: [],
    contains: ["dairy"],
    animal: true,
    kcal: 61.0,
    proteinG: 3.15,
    fatG: 3.25,
    carbG: 4.8,
    sugarG: 5.05,
    fiberG: 0.0,
    fdcId: 171265,
    fdcDescription: "Milk, whole, 3.25% milkfat, with added vitamin D",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Soy milk",
    category: "liquid",
    benefits: ["protein-power"],
    skinBenefitKey: null,
    description: "Unsweetened soy milk. Close to dairy on protein without the dairy.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "liquid",
    servingGrams: 200.0,
    hex: "#F0E9D8",
    flavors: [],
    contains: ["soy"],
    animal: false,
    kcal: 33.0,
    proteinG: 2.88,
    fatG: 1.65,
    carbG: 1.65,
    sugarG: 0.41,
    fiberG: 0.4,
    fdcId: 175223,
    fdcDescription: "SILK Unsweetened, soymilk",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Cold green tea",
    category: "liquid",
    benefits: ["energy-focus"],
    skinBenefitKey: null,
    description: "Cold-brewed green tea. Adds caffeine and a grassy edge without calories.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "liquid",
    servingGrams: 200.0,
    hex: "#CBD8A6",
    flavors: ["green-earthy"],
    contains: [],
    animal: false,
    kcal: 0.0,
    proteinG: 0.0,
    fatG: 0.0,
    carbG: 0.0,
    sugarG: 0.0,
    fiberG: 0.0,
    fdcId: 171910,
    fdcDescription: "Beverages, tea, green, brewed, decaffeinated",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Pea protein",
    category: "protein",
    benefits: ["protein-power"],
    skinBenefitKey: null,
    description: "Pea protein isolate. Plant protein with a fuller body than whey.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "protein",
    servingGrams: 30.0,
    hex: "#DCD9B8",
    flavors: [],
    contains: [],
    animal: false,
    kcal: null,
    proteinG: null,
    fatG: null,
    carbG: null,
    sugarG: null,
    fiberG: null,
    fdcId: null,
    fdcDescription: null,
    fdcDataType: null,
    nutritionNote: "No pea protein isolate in Foundation or SR Legacy; the search hit soy protein isolate, a different ingredient.",
  },
  {
    name: "Greek yogurt",
    category: "protein",
    benefits: ["gut-health", "protein-power"],
    skinBenefitKey: null,
    description: "Plain Greek yoghurt. Thickens the glass and brings both protein and live cultures.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "protein",
    servingGrams: 120.0,
    hex: "#FBF8F1",
    flavors: [],
    contains: ["dairy"],
    animal: true,
    kcal: 97.0,
    proteinG: 9.0,
    fatG: 5.0,
    carbG: 3.98,
    sugarG: 4.0,
    fiberG: 0.0,
    fdcId: 171304,
    fdcDescription: "Yogurt, Greek, plain, whole milk",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Silken tofu",
    category: "protein",
    benefits: ["protein-power"],
    skinBenefitKey: null,
    description: "Silken tofu. Blends invisibly and adds body along with plant protein.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "protein",
    servingGrams: 100.0,
    hex: "#F4F0E2",
    flavors: [],
    contains: ["soy"],
    animal: false,
    kcal: 62.0,
    proteinG: 6.9,
    fatG: 2.7,
    carbG: 2.4,
    sugarG: 1.27,
    fiberG: 0.1,
    fdcId: 172461,
    fdcDescription: "MORI-NU, Tofu, silken, firm",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Banana",
    category: "fruit",
    benefits: ["gut-health", "protein-power"],
    skinBenefitKey: null,
    description: "Banana. The default thickener — sweet, creamy, and the reason many smoothies hold their shape.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 120.0,
    hex: "#F2E3A8",
    flavors: ["vanilla-spice"],
    contains: [],
    animal: false,
    kcal: 89.0,
    proteinG: 1.09,
    fatG: 0.33,
    carbG: 22.84,
    sugarG: 12.23,
    fiberG: 2.6,
    fdcId: 173944,
    fdcDescription: "Bananas, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Strawberries",
    category: "fruit",
    benefits: ["glowy-skin"],
    skinBenefitKey: null,
    description: "Strawberries. Bright and low in sugar for a berry.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 100.0,
    hex: "#E4565C",
    flavors: ["berry"],
    contains: [],
    animal: false,
    kcal: 32.0,
    proteinG: 0.67,
    fatG: 0.3,
    carbG: 7.68,
    sugarG: 4.89,
    fiberG: 2.0,
    fdcId: 167762,
    fdcDescription: "Strawberries, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Tart cherries",
    category: "fruit",
    benefits: ["anti-inflammatory"],
    skinBenefitKey: null,
    description: "Tart cherries. Sharper than sweet cherries, and traditionally taken after hard training.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 80.0,
    hex: "#9C2B3B",
    flavors: ["berry"],
    contains: [],
    animal: false,
    kcal: 50.0,
    proteinG: 1.0,
    fatG: 0.3,
    carbG: 12.18,
    sugarG: 8.49,
    fiberG: 1.6,
    fdcId: 173954,
    fdcDescription: "Cherries, sour, red, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Pineapple",
    category: "fruit",
    benefits: ["gut-health"],
    skinBenefitKey: null,
    description: "Pineapple. Tropical and sweet, with bromelain.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 100.0,
    hex: "#F0D264",
    flavors: ["tropical"],
    contains: [],
    animal: false,
    kcal: 54.05,
    proteinG: 0.46,
    fatG: 0.21,
    carbG: 14.09,
    sugarG: 11.42,
    fiberG: 0.93,
    fdcId: 2346398,
    fdcDescription: "Pineapple, raw",
    fdcDataType: "Foundation",
    nutritionNote: null,
  },
  {
    name: "Orange",
    category: "fruit",
    benefits: ["glowy-skin"],
    skinBenefitKey: null,
    description: "Orange. Citrus lift and vitamin C.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 100.0,
    hex: "#EE8B32",
    flavors: ["citrus"],
    contains: [],
    animal: false,
    kcal: 47.0,
    proteinG: 0.94,
    fatG: 0.12,
    carbG: 11.75,
    sugarG: 9.35,
    fiberG: 2.4,
    fdcId: 169097,
    fdcDescription: "Oranges, raw, all commercial varieties",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Lemon juice",
    category: "fruit",
    benefits: ["energy-focus"],
    skinBenefitKey: null,
    description: "Lemon juice. A small amount sharpens everything else in the glass.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 15.0,
    hex: "#EFDD5E",
    flavors: ["citrus"],
    contains: [],
    animal: false,
    kcal: 22.0,
    proteinG: 0.35,
    fatG: 0.24,
    carbG: 6.9,
    sugarG: 2.52,
    fiberG: 0.3,
    fdcId: 167747,
    fdcDescription: "Lemon juice, raw",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Cacao powder",
    category: "superfood",
    benefits: ["anti-inflammatory", "energy-focus"],
    skinBenefitKey: null,
    description: "Unsweetened cacao powder. Deep chocolate flavour with no added sugar.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 10.0,
    hex: "#5A3A2E",
    flavors: ["chocolate-nutty"],
    contains: [],
    animal: false,
    kcal: 228.0,
    proteinG: 19.6,
    fatG: 13.7,
    carbG: 57.9,
    sugarG: 1.75,
    fiberG: 37.0,
    fdcId: 169593,
    fdcDescription: "Cocoa, dry powder, unsweetened",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Peanut butter",
    category: "fat",
    benefits: ["protein-power"],
    skinBenefitKey: null,
    description: "Peanut butter. Rich and filling; the single biggest calorie contributor here.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 20.0,
    hex: "#B87A42",
    flavors: ["chocolate-nutty"],
    contains: ["peanut"],
    animal: false,
    kcal: 520.0,
    proteinG: 25.9,
    fatG: 34.0,
    carbG: 35.65,
    sugarG: 9.28,
    fiberG: 5.2,
    fdcId: 172458,
    fdcDescription: "Peanut butter, smooth, reduced fat",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Almond butter",
    category: "fat",
    benefits: [],
    skinBenefitKey: null,
    description: "Almond butter. Similar to peanut butter, milder in flavour.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 20.0,
    hex: "#C09466",
    flavors: ["chocolate-nutty"],
    contains: ["tree-nut"],
    animal: false,
    kcal: 614.0,
    proteinG: 20.96,
    fatG: 55.5,
    carbG: 18.82,
    sugarG: 6.27,
    fiberG: 10.3,
    fdcId: 168603,
    fdcDescription: "Nuts, almond butter, plain, with salt added",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Vanilla",
    category: "adaptogen",
    benefits: [],
    skinBenefitKey: null,
    description: "Vanilla extract. Rounds off sharp edges and makes a glass taste sweeter than it is.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 5.0,
    hex: "#EBDFC2",
    flavors: ["vanilla-spice"],
    contains: [],
    animal: false,
    kcal: 288.0,
    proteinG: 0.06,
    fatG: 0.06,
    carbG: 12.65,
    sugarG: 12.65,
    fiberG: 0.0,
    fdcId: 173471,
    fdcDescription: "Vanilla extract",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Cinnamon",
    category: "adaptogen",
    benefits: [],
    skinBenefitKey: null,
    description: "Ground cinnamon. Warmth without sugar.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "flavor",
    servingGrams: 3.0,
    hex: "#A9622F",
    flavors: ["vanilla-spice"],
    contains: [],
    animal: false,
    kcal: 247.0,
    proteinG: 3.99,
    fatG: 1.24,
    carbG: 80.59,
    sugarG: 2.17,
    fiberG: 53.1,
    fdcId: 171320,
    fdcDescription: "Spices, cinnamon, ground",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Espresso shot",
    category: "liquid",
    benefits: ["energy-focus"],
    skinBenefitKey: null,
    description: "A shot of espresso. Caffeine and bitterness, for the mornings that need it.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "functional",
    servingGrams: 30.0,
    hex: "#3B2318",
    flavors: ["chocolate-nutty"],
    contains: [],
    animal: false,
    kcal: 9.0,
    proteinG: 0.12,
    fatG: 0.18,
    carbG: 1.67,
    sugarG: 0.0,
    fiberG: 0.0,
    fdcId: 171891,
    fdcDescription: "Beverages, coffee, brewed, espresso, restaurant-prepared",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Ground flaxseed",
    category: "superfood",
    benefits: ["glowy-skin", "gut-health"],
    skinBenefitKey: null,
    description: "Ground flaxseed. Fibre and omega-3s, with a nutty finish.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "functional",
    servingGrams: 12.0,
    hex: "#9C7B4F",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 534.0,
    proteinG: 18.29,
    fatG: 42.16,
    carbG: 28.88,
    sugarG: 1.55,
    fiberG: 27.3,
    fdcId: 169414,
    fdcDescription: "Seeds, flaxseed",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Beetroot",
    category: "vegetable",
    benefits: ["energy-focus"],
    skinBenefitKey: null,
    description: "Raw beetroot. Earthy, deeply coloured, and the reason a glass can turn magenta.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "functional",
    servingGrams: 60.0,
    hex: "#8C2749",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 40.97,
    proteinG: 1.69,
    fatG: 0.3,
    carbG: 8.79,
    sugarG: 5.1,
    fiberG: 3.12,
    fdcId: 2685576,
    fdcDescription: "Beets, raw",
    fdcDataType: "Foundation",
    nutritionNote: null,
  },
  {
    name: "Rolled oats",
    category: "superfood",
    benefits: ["gut-health", "protein-power"],
    skinBenefitKey: null,
    description: "Rolled oats. Thicken the glass and slow it down — the difference between a drink and a meal.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "thickener",
    servingGrams: 40.0,
    hex: "#DCCDA8",
    flavors: [],
    contains: ["gluten"],
    animal: false,
    kcal: 379.0,
    proteinG: 13.15,
    fatG: 6.52,
    carbG: 67.7,
    sugarG: 0.99,
    fiberG: 10.1,
    fdcId: 173904,
    fdcDescription: "Cereals, oats, regular and quick, not fortified, dry",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Chia seeds",
    category: "superfood",
    benefits: ["gut-health"],
    skinBenefitKey: null,
    description: "Chia seeds. Absorb liquid and set the texture; add them last.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "thickener",
    servingGrams: 15.0,
    hex: "#4A4038",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 486.0,
    proteinG: 16.54,
    fatG: 30.74,
    carbG: 42.12,
    sugarG: null,
    fiberG: 34.4,
    fdcId: 170554,
    fdcDescription: "Seeds, chia seeds, dried",
    fdcDataType: "SR Legacy",
    nutritionNote: "USDA publishes no sugar figure for this record; excluded from sugar totals.",
  },
  {
    name: "Ice",
    category: "liquid",
    benefits: [],
    skinBenefitKey: null,
    description: "Ice. Volume and chill, nothing else.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "thickener",
    servingGrams: 80.0,
    hex: "#E8F1F5",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 0.0,
    proteinG: 0.0,
    fatG: 0.0,
    carbG: 0.0,
    sugarG: 0.0,
    fiberG: 0.0,
    fdcId: null,
    fdcDescription: null,
    fdcDataType: null,
    nutritionNote: "Plain water. No record needed and none invented.",
  },
  {
    name: "Medjool date",
    category: "fruit",
    benefits: [],
    skinBenefitKey: null,
    description: "Medjool date. The sweetest thing in the catalog by some distance.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "sweetener",
    servingGrams: 24.0,
    hex: "#7A4A2B",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 277.0,
    proteinG: 1.81,
    fatG: 0.15,
    carbG: 74.97,
    sugarG: 66.47,
    fiberG: 6.7,
    fdcId: 168191,
    fdcDescription: "Dates, medjool",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Honey",
    category: "fruit",
    benefits: [],
    skinBenefitKey: null,
    description: "Honey. Sweetens without changing the texture.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "sweetener",
    servingGrams: 15.0,
    hex: "#D9A526",
    flavors: [],
    contains: [],
    animal: true,
    kcal: 304.0,
    proteinG: 0.3,
    fatG: 0.0,
    carbG: 82.4,
    sugarG: 82.12,
    fiberG: 0.2,
    fdcId: 169640,
    fdcDescription: "Honey",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
  {
    name: "Maple syrup",
    category: "fruit",
    benefits: [],
    skinBenefitKey: null,
    description: "Maple syrup. Sweetens with a little more character than honey.",
    koreanName: null,
    nutrientHighlights: [],
    slot: "sweetener",
    servingGrams: 15.0,
    hex: "#B5701F",
    flavors: [],
    contains: [],
    animal: false,
    kcal: 260.0,
    proteinG: 0.04,
    fatG: 0.06,
    carbG: 67.04,
    sugarG: 60.46,
    fiberG: 0.0,
    fdcId: 169661,
    fdcDescription: "Syrups, maple",
    fdcDataType: "SR Legacy",
    nutritionNote: null,
  },
];

const recipes = [
  {
    name: "The Glow Ritual",
    slug: "the-glow-ritual",
    category: "smoothie",
    tagline: "Your daily skin supplement, liquefied.",
    description: "Inspired by the Korean 'glass skin' philosophy — a complexion so luminous it appears backlit. This blend delivers vitamin C, collagen precursors, and potent antioxidants in a single ritual.",
    prepTimeMinutes: 5,
    servings: 1,
    calories: 280,
    protein: 12,
    benefits: ["glowy-skin", "anti-inflammatory"],
    skinBenefitScore: 10,
    ingredients: [
      { name: "Mango", amount: "1", unit: "cup", benefit: "Vitamin C brightening" },
      { name: "Dragon Fruit", amount: "1/2", unit: "cup", benefit: "Betalain antioxidants" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Collagen synthesis" },
      { name: "Coconut Water", amount: "3/4", unit: "cup", benefit: "Electrolyte hydration" },
      { name: "Turmeric", amount: "1/4", unit: "tsp", benefit: "Curcumin brightening" },
    ],
    steps: [
      "Freeze mango and dragon fruit overnight for a creamier texture.",
      "Add coconut water to the blender first.",
      "Layer in frozen fruits, collagen peptides, and turmeric.",
      "Blend on high for 45 seconds until completely smooth.",
      "Pour into a chilled glass. Do not dilute with ice.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["glow", "collagen", "vitamin-c", "korean-beauty"],
  },
  {
    name: "Jade Depth",
    slug: "jade-depth",
    category: "smoothie",
    tagline: "Forty shades of green. One purpose: clarity.",
    description: "A deep-chlorophyll detox smoothie drawing from Japan's matcha tradition and Korea's doenjang fermentation culture. Designed to alkalinize, energize, and restore after excess.",
    prepTimeMinutes: 5,
    servings: 1,
    calories: 195,
    protein: 8,
    benefits: ["detox-clarity", "anti-inflammatory"],
    skinBenefitScore: 8,
    ingredients: [
      { name: "Spinach", amount: "2", unit: "cups", benefit: "Chlorophyll detox" },
      { name: "Matcha", amount: "1", unit: "tsp", benefit: "EGCG antioxidants" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Healthy fat absorption" },
      { name: "Ginger", amount: "1", unit: "inch", benefit: "Circulation activation" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolyte base" },
    ],
    steps: [
      "Peel and roughly chop fresh ginger.",
      "Add coconut water and spinach first, blend until liquid.",
      "Add matcha, avocado, and ginger. Blend 60 seconds on high.",
      "Taste for balance — add a squeeze of lime if desired.",
      "Serve immediately at room temperature for optimal enzyme activity.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1622484211771-9b93ca12b41e?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["detox", "matcha", "alkaline", "energy"],
  },
  {
    name: "Cloud Nine Shaker",
    slug: "cloud-nine-shaker",
    category: "shaker",
    tagline: "Muscle recovery as a meditative act.",
    description: "Engineered for the serious athlete who refuses to compromise on flavor. 40g of clean protein with a vanilla-coconut base that tastes like dessert and performs like medicine.",
    prepTimeMinutes: 3,
    servings: 1,
    calories: 420,
    protein: 42,
    benefits: ["protein-power"],
    skinBenefitScore: 5,
    ingredients: [
      { name: "Whey Protein Isolate", amount: "2", unit: "scoops", benefit: "Muscle protein synthesis" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Healthy fats for recovery" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolyte replenishment" },
      { name: "Blueberry", amount: "1/2", unit: "cup", benefit: "Anthocyanin recovery boost" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Joint and tissue repair" },
    ],
    steps: [
      "Combine coconut water and frozen blueberries in blender.",
      "Add avocado, protein, and collagen.",
      "Blend 30 seconds — the avocado creates a silky, creamy texture.",
      "Consume within 30 minutes post-training for maximum synthesis window.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["protein", "recovery", "post-workout", "performance"],
  },
  {
    name: "Soleil Protocol",
    slug: "soleil-protocol",
    category: "smoothie",
    tagline: "Wear sunscreen. Drink this.",
    description: "Lycopene from tomato, beta-carotene from mango, and citrulline from watermelon — three scientifically validated UV defense compounds in one glass. Not a replacement for SPF; a complement to it.",
    prepTimeMinutes: 7,
    servings: 1,
    calories: 190,
    protein: 4,
    benefits: ["sun-ritual", "hydration"],
    skinBenefitScore: 9,
    ingredients: [
      { name: "Watermelon", amount: "2", unit: "cups", benefit: "Citrulline & lycopene" },
      { name: "Tomato", amount: "1", unit: "medium", benefit: "UV-protective lycopene" },
      { name: "Mango", amount: "1/2", unit: "cup", benefit: "Beta-carotene defense" },
      { name: "Ginger", amount: "1/2", unit: "inch", benefit: "Anti-inflammatory base" },
    ],
    steps: [
      "Blend watermelon chunks until liquid. Strain if desired for a cleaner texture.",
      "Add tomato, mango, and ginger. Blend 60 seconds.",
      "Consume in the morning alongside your SPF application.",
      "Best enjoyed fresh — lycopene bioavailability peaks at room temperature.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1560717845-968823efbee1?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["sun-protection", "lycopene", "hydration", "morning"],
  },
  {
    name: "Microbiome Reset Bowl",
    slug: "microbiome-reset-bowl",
    category: "meal",
    tagline: "Feed your second brain. Illuminate your skin.",
    description: "A fermented-food meal built on the gut-skin axis — the scientific understanding that what happens in your microbiome is directly reflected in your complexion. Probiotic-rich and anti-inflammatory.",
    prepTimeMinutes: 10,
    servings: 1,
    calories: 380,
    protein: 18,
    benefits: ["glowy-skin", "anti-inflammatory"],
    skinBenefitScore: 9,
    ingredients: [
      { name: "Kefir", amount: "1/2", unit: "cup", benefit: "50+ probiotic strains" },
      { name: "Blueberry", amount: "1", unit: "cup", benefit: "Anthocyanin anti-aging" },
      { name: "Avocado", amount: "1/2", unit: "whole", benefit: "Barrier-repairing fats" },
      { name: "Spirulina", amount: "1", unit: "tsp", benefit: "Phycocyanin detox" },
      { name: "Matcha", amount: "1/2", unit: "tsp", benefit: "EGCG protection" },
    ],
    steps: [
      "Pour kefir into a wide bowl as the base.",
      "Slice avocado and arrange over the kefir.",
      "Add blueberries in a single layer.",
      "Dust with spirulina and matcha using a fine sieve for an even coat.",
      "Eat slowly. This is a ritual, not a meal to rush.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1494597564530-871f2b93ac55?w=800",
    isFeatured: false,
    difficulty: "easy",
    tags: ["gut-health", "probiotics", "breakfast", "bowl"],
  },
  {
    name: "Phoenix Shaker",
    slug: "phoenix-shaker",
    category: "shaker",
    tagline: "For when you need to rebuild from the ground up.",
    description: "A high-protein, anti-inflammatory blend designed for intense training phases. Spirulina provides complete protein; turmeric accelerates recovery; collagen repairs connective tissue.",
    prepTimeMinutes: 3,
    servings: 1,
    calories: 380,
    protein: 38,
    benefits: ["protein-power", "anti-inflammatory"],
    skinBenefitScore: 6,
    ingredients: [
      { name: "Whey Protein Isolate", amount: "1.5", unit: "scoops", benefit: "Muscle synthesis" },
      { name: "Spirulina", amount: "1", unit: "tsp", benefit: "Complete amino profile" },
      { name: "Turmeric", amount: "1/2", unit: "tsp", benefit: "Curcumin recovery" },
      { name: "Blueberry", amount: "1/2", unit: "cup", benefit: "Antioxidant protection" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Connective tissue repair" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolyte base" },
    ],
    steps: [
      "Add coconut water and blueberries. Blend until smooth.",
      "Add protein, collagen, spirulina, and turmeric.",
      "Blend on high 30 seconds. The spirulina will deepen the color — this is correct.",
      "Drink within 45 minutes of training. The curcumin absorption window peaks here.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800",
    isFeatured: false,
    difficulty: "easy",
    tags: ["protein", "recovery", "anti-inflammatory", "performance"],
  },
  {
    name: "Pearl Dew",
    slug: "pearl-dew",
    category: "smoothie",
    tagline: "Drink your moisturizer.",
    description: "Hyaluronic acid lives in your skin — and you can boost its production with the right foods. This pale, delicate blend is named for the Korean beauty ideal: skin like a freshwater pearl.",
    prepTimeMinutes: 5,
    servings: 1,
    calories: 230,
    protein: 9,
    benefits: ["hydration", "glowy-skin"],
    skinBenefitScore: 10,
    ingredients: [
      { name: "Dragon Fruit", amount: "1", unit: "cup", benefit: "Hyaluronic precursors" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Plasma-matching electrolytes" },
      { name: "Kefir", amount: "1/4", unit: "cup", benefit: "Probiotic skin flora" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Dermal collagen" },
    ],
    steps: [
      "Use white-fleshed dragon fruit for the ethereal pale color.",
      "Blend kefir and coconut water first until combined.",
      "Add dragon fruit and collagen. Blend 30 seconds.",
      "The texture should be silky and thin — resist adding ice.",
      "Serve in a clear glass to appreciate the translucent pearl tone.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["hydration", "collagen", "glass-skin", "korean-beauty"],
  },
  {
    name: "Golden Hour",
    slug: "golden-hour",
    category: "smoothie",
    tagline: "Inflammation doesn't stand a chance.",
    description: "A full-spectrum anti-inflammatory blend inspired by the Haenyeo — Korean free-divers who protect their skin and joints with traditional tonic herbs. Warm, grounding, and deeply restorative.",
    prepTimeMinutes: 8,
    servings: 1,
    calories: 260,
    protein: 6,
    benefits: ["anti-inflammatory", "hydration"],
    skinBenefitScore: 8,
    ingredients: [
      { name: "Mango", amount: "1", unit: "cup", benefit: "Vitamin C synergy" },
      { name: "Turmeric", amount: "1", unit: "tsp", benefit: "Curcumin anti-inflammatory" },
      { name: "Ginger", amount: "1", unit: "inch", benefit: "Gingerol activation" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Fat for curcumin absorption" },
      { name: "Coconut Water", amount: "3/4", unit: "cup", benefit: "Hydration carrier" },
    ],
    steps: [
      "Combine all ingredients in blender. The avocado is critical — curcumin is fat-soluble.",
      "Add a crack of black pepper (optional but increases curcumin bioavailability by 2000%).",
      "Blend 60 seconds on high until silky.",
      "The color should be deep amber-gold. Serve warm or at room temperature.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1571006682516-49d1de9cc8ef?w=800",
    isFeatured: false,
    difficulty: "easy",
    tags: ["anti-inflammatory", "turmeric", "haenyeo", "restorative"],
  },
];

const plans = [
  {
    name: "The Ritualist",
    tagline: "For the curious beginner ready to build intentionally.",
    pricePerMonth: 12,
    features: [
      "Full recipe library access",
      "Smoothie Builder with live benefit scoring",
      "Save unlimited favorites",
      "Publish 3 creations per month",
      "Community wall access",
    ],
    isPopular: false,
    accentHex: "#4fb286",
  },
  {
    name: "The Alchemist",
    tagline: "Our most loved plan — for daily blend builders.",
    pricePerMonth: 24,
    features: [
      "Everything in The Ritualist",
      "Unlimited creation publishing",
      "Seasonal ingredient drops & limited recipes",
      "Personalized weekly blend plan by goal",
      "Early access to new benefit protocols",
      "Member-only ingredient sourcing guide",
    ],
    isPopular: true,
    accentHex: "#f4a259",
  },
  {
    name: "The Founder's Circle",
    tagline: "Concierge-level nutrition for the fully committed.",
    pricePerMonth: 59,
    features: [
      "Everything in The Alchemist",
      "Quarterly 1:1 session with our nutrition team",
      "Custom benefit protocol built for your skin & goals",
      "Ingredient box delivery discounts (Bay Area)",
      "Vote on next month's featured rituals",
      "Founding member badge on all your creations",
    ],
    isPopular: false,
    accentHex: "#8e5572",
  },
];

const creations = [
  {
    name: "Morning Glass Skin",
    authorName: "Yuna Park",
    authorInitials: "YP",
    goal: "glowy-skin",
    story: "I built this after my esthetician in Seoul told me to eat my skincare, not just apply it. Three weeks in and my coworkers keep asking what changed.",
    ingredients: [
      { name: "Dragon Fruit", amount: "1", unit: "cup", benefit: "Radiance boost" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Elasticity" },
      { name: "Mango", amount: "1/2", unit: "cup", benefit: "Vitamin C" },
      { name: "Kefir", amount: "1/4", unit: "cup", benefit: "Gut-skin axis" },
    ],
    likes: 128,
    colorHex: "#ff8fa3",
  },
  {
    name: "Marathon Fuel v3",
    authorName: "Diego Ramirez",
    authorInitials: "DR",
    goal: "protein-power",
    story: "Third iteration. The avocado was the unlock — no more chalky protein texture. This got me through SF Marathon training.",
    ingredients: [
      { name: "Whey Protein Isolate", amount: "2", unit: "scoops", benefit: "42g protein" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Silky texture + fats" },
      { name: "Blueberry", amount: "1/2", unit: "cup", benefit: "Recovery" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolytes" },
    ],
    likes: 94,
    colorHex: "#7b6d8d",
  },
  {
    name: "Tahoe Sun Shield",
    authorName: "Maren Olsen",
    authorInitials: "MO",
    goal: "sun-ritual",
    story: "Ski patrol taught me SPF. Smoothy King taught me lycopene. I drink this every morning before the slopes now.",
    ingredients: [
      { name: "Watermelon", amount: "2", unit: "cups", benefit: "Citrulline hydration" },
      { name: "Tomato", amount: "1", unit: "medium", benefit: "Lycopene UV defense" },
      { name: "Ginger", amount: "1/2", unit: "inch", benefit: "Circulation" },
    ],
    likes: 76,
    colorHex: "#f07167",
  },
  {
    name: "The 3pm Reset",
    authorName: "Priya Nair",
    authorInitials: "PN",
    goal: "detox-clarity",
    story: "Replaced my afternoon espresso with this. The matcha gives calm focus and the chlorophyll makes me feel like I rebooted.",
    ingredients: [
      { name: "Spinach", amount: "2", unit: "cups", benefit: "Chlorophyll" },
      { name: "Matcha", amount: "1", unit: "tsp", benefit: "L-theanine focus" },
      { name: "Ginger", amount: "1", unit: "inch", benefit: "Digestion" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Hydration" },
    ],
    likes: 63,
    colorHex: "#4fb286",
  },
  {
    name: "Post-Surf Salve",
    authorName: "Kai Nakamura",
    authorInitials: "KN",
    goal: "anti-inflammatory",
    story: "Ocean Beach in January is brutal on the joints. Turmeric plus black pepper is the oldest trick in the book because it works.",
    ingredients: [
      { name: "Turmeric", amount: "1", unit: "tsp", benefit: "Curcumin" },
      { name: "Mango", amount: "1", unit: "cup", benefit: "Vitamin C synergy" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Curcumin absorption" },
      { name: "Ginger", amount: "1", unit: "inch", benefit: "Gingerols" },
    ],
    likes: 51,
    colorHex: "#f4a259",
  },
  {
    name: "Desert Hair Hydra",
    authorName: "Amara Diallo",
    authorInitials: "AD",
    goal: "hydration",
    story: "Burning Man dehydrated me for a week straight. Built this recovery blend when I got back and now it's my daily baseline.",
    ingredients: [
      { name: "Watermelon", amount: "1.5", unit: "cups", benefit: "92% water + citrulline" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Plasma electrolytes" },
      { name: "Dragon Fruit", amount: "1/2", unit: "cup", benefit: "Skin moisture" },
    ],
    likes: 47,
    colorHex: "#59c3c3",
  },
];

export async function seed() {
  logger.info("Seeding database...");

  // Seed ingredients
  const existingIngredients = await db.select().from(ingredientsTable);
  if (existingIngredients.length === 0) {
    await db.insert(ingredientsTable).values(ingredients);
    logger.info({ count: ingredients.length }, "Seeded ingredients");
  }

  // Seed recipes
  const existingRecipes = await db.select().from(recipesTable);
  if (existingRecipes.length === 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await db.insert(recipesTable).values(recipes as any);
    logger.info({ count: recipes.length }, "Seeded recipes");
  }

  // Seed plans
  const existingPlans = await db.select().from(plansTable);
  if (existingPlans.length === 0) {
    await db.insert(plansTable).values(plans);
    logger.info({ count: plans.length }, "Seeded plans");
  }

  // Seed community creations
  const existingCreations = await db.select().from(creationsTable);
  if (existingCreations.length === 0) {
    await db.insert(creationsTable).values(creations);
    logger.info({ count: creations.length }, "Seeded creations");
  }

  logger.info("Seeding complete.");
}
