import { db, recipesTable, ingredientsTable } from "@workspace/db";
import { logger } from "./logger";

const ingredients = [
  {
    name: "Mango",
    category: "fruit",
    benefits: ["glowy-skin", "anti-inflammatory"],
    skinBenefitKey: "vitamin-c-boost",
    description: "Rich in vitamins A and C, mango brightens and evens skin tone while fighting free radicals — the K-beauty equivalent of vitamin C serum, in fruit form.",
    koreanName: "망고",
    nutrientHighlights: ["Vitamin C", "Vitamin A", "Beta-Carotene", "Folate"],
  },
  {
    name: "Dragon Fruit",
    category: "fruit",
    benefits: ["glowy-skin", "hydration"],
    skinBenefitKey: "radiance",
    description: "The hyaluronic acid of fruits. Dragon fruit is a hydration powerhouse with betalains that reduce oxidative stress and promote a luminous, dewy complexion.",
    koreanName: "드래곤 프루트",
    nutrientHighlights: ["Betalains", "Vitamin C", "Iron", "Magnesium"],
  },
  {
    name: "Turmeric",
    category: "adaptogen",
    benefits: ["anti-inflammatory", "glowy-skin"],
    skinBenefitKey: "brightening",
    description: "Curcumin, the active compound in turmeric, has been used in Korean and Ayurvedic beauty rituals for centuries. It inhibits melanin production and reduces redness at the cellular level.",
    koreanName: "강황",
    nutrientHighlights: ["Curcumin", "Manganese", "Iron", "Vitamin B6"],
  },
  {
    name: "Spirulina",
    category: "superfood",
    benefits: ["detox", "anti-inflammatory", "protein"],
    skinBenefitKey: "detox",
    description: "Nature's most concentrated protein — 70% by weight. Spirulina's phycocyanin binds to toxins and carries them out of the body, leaving skin noticeably clearer within weeks.",
    koreanName: "스피루리나",
    nutrientHighlights: ["Phycocyanin", "Complete Protein", "Iron", "B12"],
  },
  {
    name: "Collagen Peptides",
    category: "protein",
    benefits: ["glowy-skin", "protein"],
    skinBenefitKey: "collagen-synthesis",
    description: "Hydrolyzed marine collagen — the gold standard in K-beauty ingestible skincare. Clinical studies confirm significant improvement in skin elasticity and moisture retention after 8 weeks.",
    koreanName: "콜라겐 펩타이드",
    nutrientHighlights: ["Glycine", "Proline", "Hydroxyproline", "Type I & III Collagen"],
  },
  {
    name: "Coconut Water",
    category: "liquid",
    benefits: ["hydration"],
    skinBenefitKey: "electrolyte-hydration",
    description: "Nature's isotonic drink. Coconut water matches the electrolyte profile of human plasma — it doesn't just hydrate, it rehydrates at a cellular level, plumping skin from within.",
    koreanName: "코코넛 워터",
    nutrientHighlights: ["Potassium", "Sodium", "Magnesium", "Cytokinins"],
  },
  {
    name: "Ginger",
    category: "adaptogen",
    benefits: ["anti-inflammatory", "detox"],
    skinBenefitKey: "circulation-boost",
    description: "Gingerols and shogaols improve peripheral circulation, delivering oxygen and nutrients to the skin. A warming, activating ingredient — the K-beauty answer to sluggish dull skin.",
    koreanName: "생강",
    nutrientHighlights: ["Gingerols", "Shogaols", "Zinc", "Vitamin C"],
  },
  {
    name: "Avocado",
    category: "fat",
    benefits: ["hydration", "glowy-skin"],
    skinBenefitKey: "barrier-repair",
    description: "Oleic acid and vitamin E work together to repair the skin barrier and lock in moisture — the ingestible version of a rich overnight face cream. Plumping and nourishing.",
    koreanName: "아보카도",
    nutrientHighlights: ["Oleic Acid", "Vitamin E", "Vitamin K", "Folate"],
  },
  {
    name: "Whey Protein Isolate",
    category: "protein",
    benefits: ["protein"],
    skinBenefitKey: null,
    description: "Cold-processed whey isolate with 90%+ protein content. Fast-absorbing and leucine-rich for immediate muscle protein synthesis. The clean, no-filler standard for serious performance.",
    koreanName: null,
    nutrientHighlights: ["Complete Amino Acid Profile", "Leucine", "BCAAs", "Glutamine"],
  },
  {
    name: "Tomato",
    category: "vegetable",
    benefits: ["sun-ritual", "anti-inflammatory"],
    skinBenefitKey: "uv-defense",
    description: "Lycopene-dense and scientifically proven to reduce UV-induced skin damage by up to 33% with regular consumption. Korea's dermatologists call it the edible sunscreen ingredient.",
    koreanName: "토마토",
    nutrientHighlights: ["Lycopene", "Vitamin C", "Potassium", "Beta-Carotene"],
  },
  {
    name: "Matcha",
    category: "adaptogen",
    benefits: ["anti-inflammatory", "detox"],
    skinBenefitKey: "catechin-protection",
    description: "EGCG catechins in ceremonial-grade matcha are the most potent antioxidants in the plant kingdom — neutralizing 100x more free radicals than Vitamin C. A ritual, not just a drink.",
    koreanName: "말차",
    nutrientHighlights: ["EGCG", "L-Theanine", "Chlorophyll", "Catechins"],
  },
  {
    name: "Blueberry",
    category: "fruit",
    benefits: ["anti-inflammatory", "glowy-skin"],
    skinBenefitKey: "anthocyanin-glow",
    description: "Anthocyanins in blueberries cross the blood-brain barrier and stimulate collagen production directly. Wild blueberries carry 2x the antioxidant load of cultivated varieties.",
    koreanName: "블루베리",
    nutrientHighlights: ["Anthocyanins", "Resveratrol", "Vitamin C", "Manganese"],
  },
  {
    name: "Watermelon",
    category: "fruit",
    benefits: ["hydration", "sun-ritual"],
    skinBenefitKey: "citrulline-hydration",
    description: "92% water with citrulline that converts to arginine — a vasodilator that improves blood flow and nutrient delivery to skin cells. Korean summers run on watermelon for good reason.",
    koreanName: "수박",
    nutrientHighlights: ["Citrulline", "Lycopene", "Vitamin A", "Potassium"],
  },
  {
    name: "Spinach",
    category: "vegetable",
    benefits: ["detox", "anti-inflammatory"],
    skinBenefitKey: "chlorophyll-detox",
    description: "Chlorophyll acts as a molecular mirror of hemoglobin, supporting oxygen-rich blood and efficient toxin removal. One of the few ingredients that simultaneously alkalizes, detoxes, and energizes.",
    koreanName: "시금치",
    nutrientHighlights: ["Chlorophyll", "Iron", "Folate", "Vitamin K"],
  },
  {
    name: "Kefir",
    category: "protein",
    benefits: ["glowy-skin", "anti-inflammatory"],
    skinBenefitKey: "gut-skin-axis",
    description: "The gut-skin axis is the frontier of modern dermatology. Kefir's 50+ probiotic strains optimize the microbiome, reducing systemic inflammation that manifests as acne, eczema, and dullness.",
    koreanName: "케피어",
    nutrientHighlights: ["Probiotics", "Calcium", "Vitamin K2", "B Vitamins"],
  },
];

const recipes = [
  {
    name: "The Glow Ritual",
    slug: "the-glow-ritual",
    category: "smoothie",
    tagline: "Your daily skin supplement, liquefied.",
    description: "Inspired by the Korean 'glass skin' philosophy — a complexion so luminous it appears backlit. This blend delivers vitamin C, collagen precursors, and potent antioxidants in a single ritual.",
    prepTimeMinutes: 5,
    servings: 1,
    calories: 280,
    protein: 12,
    benefits: ["glowy-skin", "anti-inflammatory"],
    skinBenefitScore: 10,
    ingredients: [
      { name: "Mango", amount: "1", unit: "cup", benefit: "Vitamin C brightening" },
      { name: "Dragon Fruit", amount: "1/2", unit: "cup", benefit: "Betalain antioxidants" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Collagen synthesis" },
      { name: "Coconut Water", amount: "3/4", unit: "cup", benefit: "Electrolyte hydration" },
      { name: "Turmeric", amount: "1/4", unit: "tsp", benefit: "Curcumin brightening" },
    ],
    steps: [
      "Freeze mango and dragon fruit overnight for a creamier texture.",
      "Add coconut water to the blender first.",
      "Layer in frozen fruits, collagen peptides, and turmeric.",
      "Blend on high for 45 seconds until completely smooth.",
      "Pour into a chilled glass. Do not dilute with ice.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["glow", "collagen", "vitamin-c", "korean-beauty"],
  },
  {
    name: "Jade Depth",
    slug: "jade-depth",
    category: "smoothie",
    tagline: "Forty shades of green. One purpose: clarity.",
    description: "A deep-chlorophyll detox smoothie drawing from Japan's matcha tradition and Korea's doenjang fermentation culture. Designed to alkalinize, energize, and restore after excess.",
    prepTimeMinutes: 5,
    servings: 1,
    calories: 195,
    protein: 8,
    benefits: ["detox", "anti-inflammatory"],
    skinBenefitScore: 8,
    ingredients: [
      { name: "Spinach", amount: "2", unit: "cups", benefit: "Chlorophyll detox" },
      { name: "Matcha", amount: "1", unit: "tsp", benefit: "EGCG antioxidants" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Healthy fat absorption" },
      { name: "Ginger", amount: "1", unit: "inch", benefit: "Circulation activation" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolyte base" },
    ],
    steps: [
      "Peel and roughly chop fresh ginger.",
      "Add coconut water and spinach first, blend until liquid.",
      "Add matcha, avocado, and ginger. Blend 60 seconds on high.",
      "Taste for balance — add a squeeze of lime if desired.",
      "Serve immediately at room temperature for optimal enzyme activity.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1622484211771-9b93ca12b41e?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["detox", "matcha", "alkaline", "energy"],
  },
  {
    name: "Cloud Nine Shaker",
    slug: "cloud-nine-shaker",
    category: "shaker",
    tagline: "Muscle recovery as a meditative act.",
    description: "Engineered for the serious athlete who refuses to compromise on flavor. 40g of clean protein with a vanilla-coconut base that tastes like dessert and performs like medicine.",
    prepTimeMinutes: 3,
    servings: 1,
    calories: 420,
    protein: 42,
    benefits: ["protein"],
    skinBenefitScore: 5,
    ingredients: [
      { name: "Whey Protein Isolate", amount: "2", unit: "scoops", benefit: "Muscle protein synthesis" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Healthy fats for recovery" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolyte replenishment" },
      { name: "Blueberry", amount: "1/2", unit: "cup", benefit: "Anthocyanin recovery boost" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Joint and tissue repair" },
    ],
    steps: [
      "Combine coconut water and frozen blueberries in blender.",
      "Add avocado, protein, and collagen.",
      "Blend 30 seconds — the avocado creates a silky, creamy texture.",
      "Consume within 30 minutes post-training for maximum synthesis window.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["protein", "recovery", "post-workout", "performance"],
  },
  {
    name: "Soleil Protocol",
    slug: "soleil-protocol",
    category: "smoothie",
    tagline: "Wear sunscreen. Drink this.",
    description: "Lycopene from tomato, beta-carotene from mango, and citrulline from watermelon — three scientifically validated UV defense compounds in one glass. Not a replacement for SPF; a complement to it.",
    prepTimeMinutes: 7,
    servings: 1,
    calories: 190,
    protein: 4,
    benefits: ["sun-ritual", "hydration"],
    skinBenefitScore: 9,
    ingredients: [
      { name: "Watermelon", amount: "2", unit: "cups", benefit: "Citrulline & lycopene" },
      { name: "Tomato", amount: "1", unit: "medium", benefit: "UV-protective lycopene" },
      { name: "Mango", amount: "1/2", unit: "cup", benefit: "Beta-carotene defense" },
      { name: "Ginger", amount: "1/2", unit: "inch", benefit: "Anti-inflammatory base" },
    ],
    steps: [
      "Blend watermelon chunks until liquid. Strain if desired for a cleaner texture.",
      "Add tomato, mango, and ginger. Blend 60 seconds.",
      "Consume in the morning alongside your SPF application.",
      "Best enjoyed fresh — lycopene bioavailability peaks at room temperature.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1560717845-968823efbee1?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["sun-protection", "lycopene", "hydration", "morning"],
  },
  {
    name: "Microbiome Reset Bowl",
    slug: "microbiome-reset-bowl",
    category: "meal",
    tagline: "Feed your second brain. Illuminate your skin.",
    description: "A fermented-food meal built on the gut-skin axis — the scientific understanding that what happens in your microbiome is directly reflected in your complexion. Probiotic-rich and anti-inflammatory.",
    prepTimeMinutes: 10,
    servings: 1,
    calories: 380,
    protein: 18,
    benefits: ["glowy-skin", "anti-inflammatory"],
    skinBenefitScore: 9,
    ingredients: [
      { name: "Kefir", amount: "1/2", unit: "cup", benefit: "50+ probiotic strains" },
      { name: "Blueberry", amount: "1", unit: "cup", benefit: "Anthocyanin anti-aging" },
      { name: "Avocado", amount: "1/2", unit: "whole", benefit: "Barrier-repairing fats" },
      { name: "Spirulina", amount: "1", unit: "tsp", benefit: "Phycocyanin detox" },
      { name: "Matcha", amount: "1/2", unit: "tsp", benefit: "EGCG protection" },
    ],
    steps: [
      "Pour kefir into a wide bowl as the base.",
      "Slice avocado and arrange over the kefir.",
      "Add blueberries in a single layer.",
      "Dust with spirulina and matcha using a fine sieve for an even coat.",
      "Eat slowly. This is a ritual, not a meal to rush.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1494597564530-871f2b93ac55?w=800",
    isFeatured: false,
    difficulty: "easy",
    tags: ["gut-health", "probiotics", "breakfast", "bowl"],
  },
  {
    name: "Phoenix Shaker",
    slug: "phoenix-shaker",
    category: "shaker",
    tagline: "For when you need to rebuild from the ground up.",
    description: "A high-protein, anti-inflammatory blend designed for intense training phases. Spirulina provides complete protein; turmeric accelerates recovery; collagen repairs connective tissue.",
    prepTimeMinutes: 3,
    servings: 1,
    calories: 380,
    protein: 38,
    benefits: ["protein", "anti-inflammatory"],
    skinBenefitScore: 6,
    ingredients: [
      { name: "Whey Protein Isolate", amount: "1.5", unit: "scoops", benefit: "Muscle synthesis" },
      { name: "Spirulina", amount: "1", unit: "tsp", benefit: "Complete amino profile" },
      { name: "Turmeric", amount: "1/2", unit: "tsp", benefit: "Curcumin recovery" },
      { name: "Blueberry", amount: "1/2", unit: "cup", benefit: "Antioxidant protection" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Connective tissue repair" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Electrolyte base" },
    ],
    steps: [
      "Add coconut water and blueberries. Blend until smooth.",
      "Add protein, collagen, spirulina, and turmeric.",
      "Blend on high 30 seconds. The spirulina will deepen the color — this is correct.",
      "Drink within 45 minutes of training. The curcumin absorption window peaks here.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=800",
    isFeatured: false,
    difficulty: "easy",
    tags: ["protein", "recovery", "anti-inflammatory", "performance"],
  },
  {
    name: "Pearl Dew",
    slug: "pearl-dew",
    category: "smoothie",
    tagline: "Drink your moisturizer.",
    description: "Hyaluronic acid lives in your skin — and you can boost its production with the right foods. This pale, delicate blend is named for the Korean beauty ideal: skin like a freshwater pearl.",
    prepTimeMinutes: 5,
    servings: 1,
    calories: 230,
    protein: 9,
    benefits: ["hydration", "glowy-skin"],
    skinBenefitScore: 10,
    ingredients: [
      { name: "Dragon Fruit", amount: "1", unit: "cup", benefit: "Hyaluronic precursors" },
      { name: "Coconut Water", amount: "1", unit: "cup", benefit: "Plasma-matching electrolytes" },
      { name: "Kefir", amount: "1/4", unit: "cup", benefit: "Probiotic skin flora" },
      { name: "Collagen Peptides", amount: "1", unit: "scoop", benefit: "Dermal collagen" },
    ],
    steps: [
      "Use white-fleshed dragon fruit for the ethereal pale color.",
      "Blend kefir and coconut water first until combined.",
      "Add dragon fruit and collagen. Blend 30 seconds.",
      "The texture should be silky and thin — resist adding ice.",
      "Serve in a clear glass to appreciate the translucent pearl tone.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1614088685112-0a760b71a3c8?w=800",
    isFeatured: true,
    difficulty: "easy",
    tags: ["hydration", "collagen", "glass-skin", "korean-beauty"],
  },
  {
    name: "Golden Hour",
    slug: "golden-hour",
    category: "smoothie",
    tagline: "Inflammation doesn't stand a chance.",
    description: "A full-spectrum anti-inflammatory blend inspired by the Haenyeo — Korean free-divers who protect their skin and joints with traditional tonic herbs. Warm, grounding, and deeply restorative.",
    prepTimeMinutes: 8,
    servings: 1,
    calories: 260,
    protein: 6,
    benefits: ["anti-inflammatory", "hydration"],
    skinBenefitScore: 8,
    ingredients: [
      { name: "Mango", amount: "1", unit: "cup", benefit: "Vitamin C synergy" },
      { name: "Turmeric", amount: "1", unit: "tsp", benefit: "Curcumin anti-inflammatory" },
      { name: "Ginger", amount: "1", unit: "inch", benefit: "Gingerol activation" },
      { name: "Avocado", amount: "1/4", unit: "whole", benefit: "Fat for curcumin absorption" },
      { name: "Coconut Water", amount: "3/4", unit: "cup", benefit: "Hydration carrier" },
    ],
    steps: [
      "Combine all ingredients in blender. The avocado is critical — curcumin is fat-soluble.",
      "Add a crack of black pepper (optional but increases curcumin bioavailability by 2000%).",
      "Blend 60 seconds on high until silky.",
      "The color should be deep amber-gold. Serve warm or at room temperature.",
    ],
    imageUrl: "https://images.unsplash.com/photo-1571006682516-49d1de9cc8ef?w=800",
    isFeatured: false,
    difficulty: "easy",
    tags: ["anti-inflammatory", "turmeric", "haenyeo", "restorative"],
  },
];

export async function seed() {
  logger.info("Seeding database...");

  // Seed ingredients
  const existingIngredients = await db.select().from(ingredientsTable);
  if (existingIngredients.length === 0) {
    await db.insert(ingredientsTable).values(ingredients);
    logger.info({ count: ingredients.length }, "Seeded ingredients");
  }

  // Seed recipes
  const existingRecipes = await db.select().from(recipesTable);
  if (existingRecipes.length === 0) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await db.insert(recipesTable).values(recipes as any);
    logger.info({ count: recipes.length }, "Seeded recipes");
  }

  logger.info("Seeding complete.");
}
